# Parent Node
FROM node:latest
# NodeMon is used to automatically restart the server on file changes
RUN npm install -g nodemon
# Set the working directory in the container
# This is where the application code will be copied
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY . .
# Install the application dependencies
# This will install all the dependencies listed in package.json
# and create a node_modules directory in the working directory
RUN npm install
# Expose port 3000 for the application
# This is the port the application will run on
EXPOSE 3000
# Start the application using nodemon
# This will run the application in development mode
CMD ["npm", "run", "dev"]